version: '3.4'

networks:
  aircoilapi:

services:
  aircoildb:
    container_name: air-coil-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    networks:
      - aircoilapi

  aircoilapi:
    container_name: air-coil-api
    image: ${DOCKER_REGISTRY-}aircoilapi
    build:
      context: .
      dockerfile: AirCoil-API/Dockerfile
    ports:
      - 5000:5000
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_SA_PASSWORD=${DB_SA_PASSWORD}
    depends_on:
      - aircoildb 
    networks:
      - aircoilapi